/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedCompanySlugRouteImport } from './routes/_authenticated/company.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedCompanySlugIndexRouteImport } from './routes/_authenticated/company.$slug.index'
import { Route as AuthenticatedCompanySlugDashboardRouteImport } from './routes/_authenticated/company.$slug.dashboard'
import { Route as AuthenticatedCompanySlugInvoiceNewRouteImport } from './routes/_authenticated/company.$slug.invoice.new'
import { Route as AuthenticatedCompanySlugDocumentIdRouteImport } from './routes/_authenticated/company.$slug.document.$id'
import { Route as AuthenticatedCompanySlugChallanNewRouteImport } from './routes/_authenticated/company.$slug.challan.new'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCompanySlugRoute =
  AuthenticatedCompanySlugRouteImport.update({
    id: '/company/$slug',
    path: '/company/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompanySlugIndexRoute =
  AuthenticatedCompanySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompanySlugRoute,
  } as any)
const AuthenticatedCompanySlugDashboardRoute =
  AuthenticatedCompanySlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCompanySlugRoute,
  } as any)
const AuthenticatedCompanySlugInvoiceNewRoute =
  AuthenticatedCompanySlugInvoiceNewRouteImport.update({
    id: '/invoice/new',
    path: '/invoice/new',
    getParentRoute: () => AuthenticatedCompanySlugRoute,
  } as any)
const AuthenticatedCompanySlugDocumentIdRoute =
  AuthenticatedCompanySlugDocumentIdRouteImport.update({
    id: '/document/$id',
    path: '/document/$id',
    getParentRoute: () => AuthenticatedCompanySlugRoute,
  } as any)
const AuthenticatedCompanySlugChallanNewRoute =
  AuthenticatedCompanySlugChallanNewRouteImport.update({
    id: '/challan/new',
    path: '/challan/new',
    getParentRoute: () => AuthenticatedCompanySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/company/$slug': typeof AuthenticatedCompanySlugRouteWithChildren
  '/company/$slug/dashboard': typeof AuthenticatedCompanySlugDashboardRoute
  '/company/$slug/': typeof AuthenticatedCompanySlugIndexRoute
  '/company/$slug/challan/new': typeof AuthenticatedCompanySlugChallanNewRoute
  '/company/$slug/document/$id': typeof AuthenticatedCompanySlugDocumentIdRoute
  '/company/$slug/invoice/new': typeof AuthenticatedCompanySlugInvoiceNewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/company/$slug/dashboard': typeof AuthenticatedCompanySlugDashboardRoute
  '/company/$slug': typeof AuthenticatedCompanySlugIndexRoute
  '/company/$slug/challan/new': typeof AuthenticatedCompanySlugChallanNewRoute
  '/company/$slug/document/$id': typeof AuthenticatedCompanySlugDocumentIdRoute
  '/company/$slug/invoice/new': typeof AuthenticatedCompanySlugInvoiceNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/company/$slug': typeof AuthenticatedCompanySlugRouteWithChildren
  '/_authenticated/company/$slug/dashboard': typeof AuthenticatedCompanySlugDashboardRoute
  '/_authenticated/company/$slug/': typeof AuthenticatedCompanySlugIndexRoute
  '/_authenticated/company/$slug/challan/new': typeof AuthenticatedCompanySlugChallanNewRoute
  '/_authenticated/company/$slug/document/$id': typeof AuthenticatedCompanySlugDocumentIdRoute
  '/_authenticated/company/$slug/invoice/new': typeof AuthenticatedCompanySlugInvoiceNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/company/$slug'
    | '/company/$slug/dashboard'
    | '/company/$slug/'
    | '/company/$slug/challan/new'
    | '/company/$slug/document/$id'
    | '/company/$slug/invoice/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/company/$slug/dashboard'
    | '/company/$slug'
    | '/company/$slug/challan/new'
    | '/company/$slug/document/$id'
    | '/company/$slug/invoice/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/company/$slug'
    | '/_authenticated/company/$slug/dashboard'
    | '/_authenticated/company/$slug/'
    | '/_authenticated/company/$slug/challan/new'
    | '/_authenticated/company/$slug/document/$id'
    | '/_authenticated/company/$slug/invoice/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/company/$slug': {
      id: '/_authenticated/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof AuthenticatedCompanySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/company/$slug/': {
      id: '/_authenticated/company/$slug/'
      path: '/'
      fullPath: '/company/$slug/'
      preLoaderRoute: typeof AuthenticatedCompanySlugIndexRouteImport
      parentRoute: typeof AuthenticatedCompanySlugRoute
    }
    '/_authenticated/company/$slug/dashboard': {
      id: '/_authenticated/company/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/company/$slug/dashboard'
      preLoaderRoute: typeof AuthenticatedCompanySlugDashboardRouteImport
      parentRoute: typeof AuthenticatedCompanySlugRoute
    }
    '/_authenticated/company/$slug/invoice/new': {
      id: '/_authenticated/company/$slug/invoice/new'
      path: '/invoice/new'
      fullPath: '/company/$slug/invoice/new'
      preLoaderRoute: typeof AuthenticatedCompanySlugInvoiceNewRouteImport
      parentRoute: typeof AuthenticatedCompanySlugRoute
    }
    '/_authenticated/company/$slug/document/$id': {
      id: '/_authenticated/company/$slug/document/$id'
      path: '/document/$id'
      fullPath: '/company/$slug/document/$id'
      preLoaderRoute: typeof AuthenticatedCompanySlugDocumentIdRouteImport
      parentRoute: typeof AuthenticatedCompanySlugRoute
    }
    '/_authenticated/company/$slug/challan/new': {
      id: '/_authenticated/company/$slug/challan/new'
      path: '/challan/new'
      fullPath: '/company/$slug/challan/new'
      preLoaderRoute: typeof AuthenticatedCompanySlugChallanNewRouteImport
      parentRoute: typeof AuthenticatedCompanySlugRoute
    }
  }
}

interface AuthenticatedCompanySlugRouteChildren {
  AuthenticatedCompanySlugDashboardRoute: typeof AuthenticatedCompanySlugDashboardRoute
  AuthenticatedCompanySlugIndexRoute: typeof AuthenticatedCompanySlugIndexRoute
  AuthenticatedCompanySlugChallanNewRoute: typeof AuthenticatedCompanySlugChallanNewRoute
  AuthenticatedCompanySlugDocumentIdRoute: typeof AuthenticatedCompanySlugDocumentIdRoute
  AuthenticatedCompanySlugInvoiceNewRoute: typeof AuthenticatedCompanySlugInvoiceNewRoute
}

const AuthenticatedCompanySlugRouteChildren: AuthenticatedCompanySlugRouteChildren =
  {
    AuthenticatedCompanySlugDashboardRoute:
      AuthenticatedCompanySlugDashboardRoute,
    AuthenticatedCompanySlugIndexRoute: AuthenticatedCompanySlugIndexRoute,
    AuthenticatedCompanySlugChallanNewRoute:
      AuthenticatedCompanySlugChallanNewRoute,
    AuthenticatedCompanySlugDocumentIdRoute:
      AuthenticatedCompanySlugDocumentIdRoute,
    AuthenticatedCompanySlugInvoiceNewRoute:
      AuthenticatedCompanySlugInvoiceNewRoute,
  }

const AuthenticatedCompanySlugRouteWithChildren =
  AuthenticatedCompanySlugRoute._addFileChildren(
    AuthenticatedCompanySlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCompanySlugRoute: typeof AuthenticatedCompanySlugRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCompanySlugRoute: AuthenticatedCompanySlugRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
